Repository fidelity/kconnect, pull requests merged in 2020-09, with the labels that each got.

#71 chore: added a synk scan github actions workflow
  .github/workflows/scan.yaml
Labels: size/xs

#66 docs: history support in kconnect proposal
  docs/proposals/20200827-history.md
Labels: size/m

#72 feat: allow setting current context
  internal/app/use.go
  internal/commands/use/use.go
  pkg/plugins/discovery/aws/config.go
  pkg/provider/types.go
Labels: size/xs

#77 chore: disable snap publishing
  .github/workflows/release.yml
  .goreleaser.yml
Labels: size/s

#81 fix: add cluster name to username of kubeconfig
  pkg/plugins/discovery/aws/config.go
Labels: size/xs

#82 feat: changed region to not defaults and updated resolvers
  go.mod
  go.sum
  internal/app/use.go
  pkg/plugins/discovery/aws/provider.go
  pkg/plugins/discovery/aws/resolver.go
  pkg/plugins/identity/saml/saml.go
  pkg/plugins/identity/saml/sp/aws/provider.go
  pkg/plugins/identity/saml/sp/aws/resolver.go
  pkg/plugins/identity/saml/sp/aws/resolver_debug.go
  pkg/plugins/identity/saml/sp/aws/resolver_interactive.go
Labels: size/m

#84 build: adding docker goreleaser support
  .goreleaser.yml
  Dockerfile
Labels: size/xs

#85 fix: added docker login to GH actions
  .github/workflows/release.yml
  .goreleaser.yml
Labels: size/xs

#91 fix: kubeconfig merge and duplicate history entries
  api/v1alpha1/history_types.go
  api/v1alpha1/zz_generated.deepcopy.go
  go.mod
  internal/app/use.go
  internal/defaults/defaults.go
  pkg/config/configuration.go
  pkg/history/filter.go
  pkg/history/loader/loader.go
  pkg/history/store.go
  pkg/history/store_test.go
  pkg/k8s/kubeconfig/kubeconfig.go
  pkg/plugins/discovery/aws/config.go
  pkg/provider/types.go
Labels: size/s

#95 fix: capitalization in usage, default log level and app folder
  .goreleaser.yml
  internal/app/config.go
  internal/app/list.go
  internal/app/to.go
  internal/app/use.go
  internal/commands/configure/configure.go
  internal/commands/ls/ls.go
  internal/commands/root.go
  internal/commands/to/to.go
  internal/commands/use/use.go
  pkg/plugins/discovery/aws/provider.go
  pkg/plugins/identity/saml/saml.go
  pkg/provider/config.go
Labels: size/s

#96 feat: add deb and rpm packaging
  .goreleaser.yml
Labels: size/xs

#97 chore: output version to log on start
  internal/app/configure.go
  internal/commands/root.go
Labels: size/xs

#101 feat: add snapcraft publishing
  internal/app/configure.go
  internal/commands/configure/configure.go
Labels: size/s
