Repository fidelity/kconnect, pull requests merged in 2020-10, with the labels that each got.

#114 fix: usage not showing correctly
  go.mod
  go.sum
  internal/app/config.go
  internal/commands/configure/configure.go
  internal/commands/ls/ls.go
  internal/commands/to/to.go
  internal/commands/use/use.go
  internal/usage/usage.go
  pkg/flags/flags.go
Labels: size/m

#117 fix: set current context when using 'to'
  internal/app/to.go
  internal/commands/configure/configure.go
  internal/commands/ls/ls.go
  internal/commands/to/to.go
  internal/commands/use/use.go
  pkg/flags/flags.go
  pkg/provider/config.go
Labels: size/s

#120 Set history on use
  internal/app/config.go
  internal/app/to.go
  internal/app/use.go
  internal/commands/root.go
  pkg/config/configset.go
  pkg/flags/flags.go
Labels: size/s

#121 refactor: changed the logging in the commands
  internal/commands/configure/configure.go
  internal/commands/ls/ls.go
  internal/commands/to/to.go
  internal/commands/use/use.go
Labels: size/s

#122 feat: alias and username in table output
  api/v1alpha1/history_types.go
Labels: size/xs

#102 docs: started to add docs site
  .github/workflows/release-docs.yml
  .gitignore
  Makefile
  README.md
  docs/book/.gitignore
  docs/book/book.toml
  docs/book/src/SUMMARY.md
  docs/book/src/commands/index.md
  docs/book/src/commands/use.md
  docs/book/src/contributing.md
  docs/book/src/getting-started.md
  docs/book/src/installation.md
  docs/book/src/introduction.md
  docs/book/theme/css/general.css
  docs/book/theme/favicon.png
  docs/book/theme/head.hbs
Labels: size/m

#127 fix: removed re-using cached credentials
  internal/app/config.go
  internal/app/use.go
  internal/commands/configure/configure.go
  internal/commands/ls/ls.go
  internal/commands/root.go
  internal/commands/to/to.go
  internal/commands/use/use.go
  pkg/config/configset.go
  pkg/plugins/discovery/aws/provider.go
  pkg/plugins/identity/saml/saml.go
  pkg/plugins/identity/saml/sp/aws/provider.go
  pkg/plugins/identity/saml/sp/aws/resolver.go
  pkg/plugins/identity/saml/sp/types.go
  pkg/provider/config.go
Labels: size/s

#130 feat: renew command
  internal/commands/renew/renew.go
  internal/commands/root.go
  pkg/history/history.go
  pkg/history/store.go
  pkg/history/store_test.go
Labels: size/m

#132 feat: add region filter
  pkg/plugins/discovery/aws/provider.go
  pkg/plugins/identity/saml/sp/aws/resolver.go
Labels: size/xs

#134 docs: setting env vars based on flag names
  docs/book/src/getting-started.md
Labels: size/xs

#135 fix: role-filter was not being used
  pkg/plugins/discovery/aws/provider.go
  pkg/plugins/identity/saml/sp/aws/provider.go
Labels: size/xs

#133 refactor: change logging from logrus to zap
  go.mod
  go.sum
  internal/app/app.go
  internal/app/config.go
  internal/app/configure.go
  internal/app/list.go
  internal/app/to.go
  internal/app/use.go
  internal/commands/configure/configure.go
  internal/commands/ls/ls.go
  internal/commands/renew/renew.go
  internal/commands/root.go
  internal/commands/to/to.go
  internal/commands/use/use.go
  main.go
  pkg/flags/flags.go
  pkg/k8s/kubeconfig/kubeconfig.go
  pkg/logging/logging.go
  pkg/plugins/discovery/aws/config.go
  pkg/plugins/discovery/aws/discover.go
  pkg/plugins/discovery/aws/get.go
  pkg/plugins/discovery/aws/provider.go
  pkg/plugins/discovery/aws/resolver.go
  pkg/plugins/identity/empty/empty.go
  pkg/plugins/identity/saml/saml.go
  pkg/plugins/identity/saml/sp/aws/provider.go
  pkg/plugins/identity/saml/sp/aws/resolver.go
  pkg/plugins/identity/saml/sp/types.go
  pkg/provider/context.go
Labels: size/m

#139 chore: enable code quality analysis
  .github/workflows/codeql-analysis.yml
Labels: size/s

#141 chore: removed the snyk GA workflow
  .github/workflows/scan.yaml
Labels: size/xs

#138 feat: change to publishing images to docker hub
  .github/workflows/release.yml
  .goreleaser.yml
Labels: size/xs

#142 chore: updated url in proposal as its misleading
  docs/proposals/20200630-cli-ux.md
Labels: size/xs

#143 chore: remove redundant code from root cmd
  internal/commands/root.go
Labels: size/xs

#148 feat: prompt for alias in interactive mode
  internal/app/use.go
Labels: size/s

#151 feat: remove renew command, add functionality to "to"
  api/v1alpha1/history_types.go
  api/v1alpha1/zz_generated.deepcopy.go
  docs/book/src/commands/index.md
  docs/book/src/commands/to.md
  go.mod
  go.sum
  hack/tools/go.sum
  internal/app/alias.go
  internal/app/to.go
  internal/app/use.go
  internal/commands/renew/renew.go
  internal/commands/root.go
  internal/commands/to/to.go
  internal/commands/use/use.go
  pkg/history/history.go
  pkg/history/store.go
  pkg/history/store_test.go
Labels: size/m

#153 feat: Profile name change
  pkg/aws/config.go
  pkg/aws/identifer.go
  pkg/plugins/discovery/aws/config.go
  pkg/plugins/discovery/aws/provider.go
  pkg/plugins/identity/saml/saml.go
  pkg/plugins/identity/saml/sp/aws/provider.go
  pkg/plugins/identity/saml/sp/aws/resolver.go
  pkg/plugins/identity/saml/sp/aws/store.go
  pkg/plugins/identity/saml/sp/types.go
Labels: size/s

#162 feat: docker hub publishing and arm builds
  .goreleaser.yml
  Dockerfile
  README.md
  docs/book/src/getting-started.md
  docs/book/src/installation.md
  internal/commands/root.go
Labels: size/s

#171 fix: running in docker resulted in permission denied
  Dockerfile
  docs/book/src/installation.md
Labels: size/xs
