Repository fidelity/kconnect, pull requests merged in 2021-02, with the labels that each got.

#288 feat: history import + export commands
  docs/book/src/commands/history.md
  docs/book/src/commands/history_export.md
  docs/book/src/commands/history_import.md
  docs/book/src/commands/index.md
  go.mod
  go.sum
  internal/app/config.go
  internal/app/history.go
  internal/commands/history/export.go
  internal/commands/history/history.go
  internal/commands/history/import.go
  internal/commands/root.go
  pkg/flags/flags.go
  pkg/flags/flags_test.go
  pkg/history/filter.go
  pkg/history/filter_test.go
  pkg/history/history.go
  pkg/history/store.go
  pkg/history/store_test.go
  pkg/utils/utils_test.go
Labels: size/m

#292 feat: add history rm command
  docs/book/src/commands/history.md
  docs/book/src/commands/history_rm.md
  go.mod
  go.sum
  internal/app/config.go
  internal/app/history.go
  internal/commands/history/history.go
  internal/commands/history/rm.go
  pkg/history/store_test.go
Labels: size/m

#297 feat: change version check error to warning
  go.mod
  internal/commands/root.go
Labels: size/xs

#284 feat: adding kubelogin support to AKS provider
  .goreleaser.yml
  docs/book/src/commands/use_aks.md
  docs/book/src/getting-started.md
  docs/book/src/installation.md
  pkg/plugins/discovery/azure/config.go
  pkg/plugins/discovery/azure/defaults.go
  pkg/plugins/discovery/azure/discover.go
  pkg/plugins/discovery/azure/provider.go
  pkg/plugins/discovery/azure/types.go
  pkg/utils/prerequisites.go
Labels: size/m

#298 fix: root peristent commands not being used
  internal/commands/alias/add.go
  internal/commands/alias/ls.go
  internal/commands/alias/remove.go
  internal/commands/config/config.go
  internal/commands/history/export.go
  internal/commands/history/import.go
  internal/commands/history/rm.go
  internal/commands/logout/logout.go
  internal/commands/ls/ls.go
  internal/commands/root.go
  internal/commands/use/use.go
  internal/helpers/common.go
  pkg/app/config.go
  pkg/app/to.go
  pkg/config/apply.go
Labels: size/s

#300 fix: panic as httpclient not peristed to provider
  pkg/plugins/identity/rancher/activedirectory/activedirectory.go
Labels: size/xs

#301 fix: providers the wrong way around
  pkg/app/to.go
Labels: size/xs

#309 feat: added oidc token auth for aks
  docs/book/src/commands/use_aks.md
  pkg/app/use.go
  pkg/azure/identity/authorizer.go
  pkg/azure/identity/errors.go
  pkg/azure/identity/identity.go
  pkg/oidc/oidc.go
  pkg/plugins/discovery/azure/config.go
  pkg/plugins/discovery/azure/errors.go
  pkg/plugins/discovery/azure/provider.go
  pkg/plugins/discovery/azure/types.go
  pkg/plugins/identity/azure/aad/aad.go
  pkg/provider/discovery/discovery.go
Labels: size/m
